# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

type: workloads.filteredann
class: FilteredAnnWorkload
config:
  search_dataset: gs://odyssey_benchmarking/datasets/cohere-10m/cohere10m-query.hdf5
  search_key: 'query'
  number_of_workers: 1
  duration_in_seconds: 0
  index_recreate: False
  index_type: 'TREE_AH'
  index_config:
    - num_leaves: 20000
  num_leaves_to_search: 269 # 10 
  algo: 'vector_cosine_ops'
  probes: 31
  search_limit: 10
  filtered_ratio: 10  # % of metadata filtered
  report_template: 'filteredann.j2'
  ground_truth_keys:
    - 'neighbors'
    - 'distances'
  ground_truth_datasets: 
    - gs://odyssey_benchmarking/datasets/cohere-10m/cohere10m-neighbors-10.hdf5
    - gs://odyssey_benchmarking/datasets/cohere-10m/cohere10m-distances-10.hdf5
